export const projects = [
  {
      title: 'MERN Stack E-Commerce Website',
      description: "Using React, Node.js, Express & MongoDB I have build a Full Stack MERN Application. The App is called E-Commerce and it is a simple app which allows the users to go through the variety of products available and buy them.",
      image: '/images/image.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
      githublink : 'https://github.com/ashar708/ecommerce',
      deploymentLinkFrontend : 'https://ecommerce-one-lake-13.vercel.app/',
      deploymentLinkBackend : 'https://ecommerce-backend-coral-eight.vercel.app/',
      readme: 'https://github.com/ashar708/ecommerce/blob/main/README.md',
      id: 0,
  },
  {
      title: 'MERN Stack Food Website',
      description: "Using React, Node.js, Express & MongoDB I have build a Full Stack MERN Application. The App is called Tomato and it is a simple app which allows the users to go through the variety of food items available and order them.",
      image: '/assets/image1.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
      githublink : 'https://github.com/ashar708/Swiggy-clone',
      deploymentLinkFrontend : 'https://swiggy-clone-frontend-2ft7.onrender.com',
      deploymentLinkBackend: 'https://swiggy-clone-nl3f.onrender.com',
      deploymentLinkAdmin: 'https://swiggy-clone-admin.onrender.com',
      readme: 'https://github.com/ashar708/Swiggy-clone/blob/main/README.md',
      id: 1,
  },
  {
    title: 'NextJS Banking App',
    description: "Using React, NextJS, Node.js, Express & MongoDB I have build a Full Stack MERN Application. The App is called Horizon and it is a simple app which allows the users to connect to different bank accounts and transfer money.",
    image: '/assets/image.png',
    tags: ['Mongo', 'NextJS', 'Express', 'React', 'Node'],
    githublink : 'https://github.com/ashar708/banking',
    deploymentLinks : 'https://banking-r1u6.vercel.app/',
    readme: 'https://github.com/ashar708/banking/blob/main/README.md',
    id: 2,
},
{
  title: 'GPT3 App',
  description: "Using React I have build a static website, with reusable components.",
  image: '/assets/image2.png',
  tags: ['React','Figma Designs'],
  githublink : 'https://github.com/ashar708/banking',
  deploymentLinks : 'https://banking-r1u6.vercel.app/',
  readme: 'https://github.com/ashar708/Restaurant-App/blob/main/README.md',
  id: 3,
},
{
  title: 'Landing Page',
  description: "Using React I have build a static website, with reusable components.",
  image: '/assets/image3.png',
  tags: ['React','Figma Designs'],
  githublink : 'https://github.com/ashar708/Landing-Page',
  deploymentLinks : 'https://landing-page-swart-seven.vercel.app/',
  readme: 'https://github.com/ashar708/Landing-Page/blob/main/README.md',
  id: 4,
},
{
  title: 'Restaurant App',
  description: "Using React I have build a static website, with reusable components.",
  image: '/assets/image4.png',
  tags: ['React','Figma Designs'],
  githublink : 'https://github.com/ashar708/Restaurant-App',
  deploymentLinks : 'https://restaurant-app-tawny-three.vercel.app/',
  readme: 'https://github.com/ashar708/Restaurant-App/blob/main/README.md',
  id: 5,
},
];

export const TimeLineData = [
  { year: 2019, text: 'Started my college', },
  { year: 2022, text: 'Internship in High Radius', },
  { year: 2023, text: 'Joined Optum as a TDP', },
  { year: 2024, text: 'Learnt about Sailpoint and Full Stack Technologies', },
];